name: nemo_full_v311
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_10
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-command-line-tools=12.9.1=0
  - cuda-compiler=11.8.0=0
  - cuda-crt-dev_linux-64=12.9.86=0
  - cuda-cudart=12.9.79=0
  - cuda-cudart-dev=12.9.79=0
  - cuda-cudart-dev_linux-64=12.9.79=0
  - cuda-cudart-static=12.9.79=0
  - cuda-cudart-static_linux-64=12.9.79=0
  - cuda-cudart_linux-64=12.9.79=0
  - cuda-cuobjdump=12.9.82=1
  - cuda-cupti=12.9.79=0
  - cuda-cupti-dev=12.9.79=0
  - cuda-cuxxfilt=12.9.82=1
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.9.79=0
  - cuda-driver-dev_linux-64=12.9.79=0
  - cuda-gdb=12.9.79=1
  - cuda-libraries=12.9.1=0
  - cuda-libraries-dev=12.9.1=0
  - cuda-nsight=12.9.79=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.9.88=1
  - cuda-nvml-dev=12.9.79=1
  - cuda-nvprof=12.9.79=0
  - cuda-nvprune=12.9.82=1
  - cuda-nvrtc=12.9.86=0
  - cuda-nvrtc-dev=12.9.86=0
  - cuda-nvtx=12.9.79=0
  - cuda-nvvp=12.9.79=1
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-sanitizer-api=12.9.79=1
  - cuda-toolkit=11.8.0=0
  - cuda-tools=12.9.1=0
  - cuda-version=12.9=3
  - cuda-visual-tools=12.9.1=0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h82a94d6_16
  - gcc_linux-64=11.2.0=h39a9532_10
  - gds-tools=1.14.1.1=4
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h82a94d6_16
  - gxx_linux-64=11.2.0=hacbe6df_10
  - icu=73.1=h6a678d5_0
  - kernel-headers_linux-64=4.18.0=he073ed8_9
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libcublas=12.9.1.4=0
  - libcublas-dev=12.9.1.4=0
  - libcufft=11.4.1.4=0
  - libcufft-dev=11.4.1.4=0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.7.5.82=0
  - libcusolver-dev=11.7.5.82=0
  - libcusparse=12.5.10.65=0
  - libcusparse-dev=12.5.10.65=0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=11.2.0=h0952999_16
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.4.1.87=0
  - libnpp-dev=12.4.1.87=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.9.82=0
  - libnvjitlink=12.9.86=0
  - libnvjitlink-dev=12.9.86=0
  - libnvjpeg=12.4.0.76=0
  - libnvjpeg-dev=12.4.0.76=0
  - libpng=1.6.50=h2ed474d_0
  - libsanitizer=11.2.0=he4da1e4_16
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=11.2.0=h0952999_16
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2025.2.1.3=0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.28=h4ee821c_9
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py311h06a4308_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - accelerated-scan==0.2.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - alembic==1.17.2
      - aniso8601==10.0.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asciitree==0.3.3
      - asttokens==3.0.1
      - attrdict==2.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - av==16.0.1
      - babel==2.17.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - black==24.10.0
      - blinker==1.9.0
      - boto3==1.42.16
      - botocore==1.42.16
      - braceexpand==0.1.7
      - bracex==2.6
      - catalogue==2.0.10
      - cdifflib==1.2.6
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clip==0.2.0
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - contextlib2==21.6.0
      - contourpy==1.3.3
      - coverage==7.13.0
      - cryptography==42.0.8
      - ctc-segmentation==1.7.4
      - cuda-bindings==13.1.1
      - cuda-core==0.5.0
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cycler==0.12.1
      - cython==3.2.3
      - cytoolz==1.1.0
      - datasets==4.4.2
      - decorator==5.2.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - diffusers==0.36.0
      - dill==0.4.0
      - docker==7.1.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - docutils==0.22.4
      - editdistance==0.8.1
      - einops==0.8.1
      - einops-exts==0.0.4
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fabric==3.2.2
      - faiss-cpu==1.13.1
      - fastapi==0.127.0
      - fasteners==0.20
      - fiddle==0.3.0
      - filelock==3.20.0
      - flask==3.1.2
      - flask-restful==0.3.10
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperframe==6.1.0
      - idna==3.11
      - ijson==3.4.0.post0
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.1
      - indic-numtowords==1.1.0
      - inflect==7.5.0
      - iniconfig==2.3.0
      - inquirerpy==0.3.4
      - intervaltree==3.2.1
      - invoke==2.2.1
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - isort==5.13.2
      - itsdangerous==2.2.0
      - janome==0.5.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiwer==3.1.0
      - jmespath==1.0.1
      - joblib==1.5.3
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kaldi-python-io==1.2.2
      - kaldialign==0.9.1
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lark==1.3.1
      - latexcodec==3.0.1
      - lazy-loader==0.4
      - ledoc-ui==0.1.0
      - leptonai==0.26.7
      - lhotse==1.32.1
      - libcst==1.8.6
      - librosa==0.11.0
      - lightning==2.4.0
      - lightning-utilities==0.15.2
      - lilcom==1.8.1
      - llvmlite==0.46.0
      - loguru==0.7.3
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - marshmallow==4.1.2
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mediapy==1.1.6
      - megatron-core==0.15.0
      - megatron-energon==5.2.0
      - ml-dtypes==0.5.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multi-storage-client==0.39.1
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - nemo-run==0.7.0
      - nemo-text-processing==1.1.0
      - nemo-toolkit==2.6.0
      - nerfacc==0.5.3
      - networkx==3.6.1
      - ninja==1.13.0
      - nltk==3.9.2
      - num2words==0.5.14
      - numba==0.63.1
      - numba-cuda==0.23.0
      - numcodecs==0.15.1
      - numexpr==2.13.1
      - numpy==1.26.4
      - nv-one-logger-core==2.3.1
      - nv-one-logger-pytorch-lightning-integration==2.3.1
      - nv-one-logger-training-telemetry==2.3.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cccl==13.1.78
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc==13.1.80
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime==13.1.80
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.590.44
      - nvidia-modelopt==0.35.0
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink==13.1.80
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - nvidia-nvvm==13.1.80
      - nvidia-resiliency-ext==0.4.1
      - nvtx==0.2.14
      - omegaconf==2.3.0
      - onnx==1.20.0
      - onnxruntime==1.23.2
      - open-clip-torch==2.24.0
      - opencc==1.1.9
      - opentelemetry-api==1.39.1
      - optree==0.18.0
      - optuna==4.6.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.3
      - pangu==4.0.6.1
      - parameterized==0.9.0
      - paramiko==4.0.0
      - parso==0.8.5
      - pathspec==0.12.1
      - peft==0.18.0
      - pesq==0.0.4
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - prettytable==3.17.0
      - progress==1.6.1
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==7.2.0
      - ptyprocess==0.7.0
      - pulp==3.3.0
      - pure-eval==0.2.3
      - pyannote-core==5.0.0
      - pyannote-database==5.1.3
      - pyannote-metrics==3.2.1
      - pyarrow==22.0.0
      - pybtex==0.25.1
      - pybtex-docutils==1.0.3
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.1.1
      - pynacl==1.6.1
      - pynini==2.1.6.post1
      - pynvml==13.0.1
      - pyparsing==3.3.1
      - pypinyin==0.55.0
      - pypinyin-dict==0.9.0
      - pyre-extensions==0.0.32
      - pysocks==1.7.1
      - pystoi==0.4.1
      - pytest==9.0.2
      - pytest-httpserver==1.1.3
      - pytest-mock==3.15.1
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.14
      - rapidfuzz==3.14.3
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - resampy==0.4.3
      - rich==14.2.0
      - roman-numerals==4.1.0
      - rouge-score==0.1.2
      - rpds-py==0.30.0
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - s3fs==0.4.2
      - s3transfer==0.16.0
      - sacrebleu==2.5.1
      - sacremoses==0.1.1
      - safetensors==0.7.0
      - scienceplots==2.2.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8.1
      - sox==1.5.0
      - soxr==1.0.0
      - sphinx==9.0.4
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-bibtex==2.6.5
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - starlette==0.50.0
      - strenum==0.4.15
      - sympy==1.13.1
      - tabulate==0.9.0
      - taming-transformers==0.0.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.71
      - text-unidecode==1.3
      - textdistance==4.6.3
      - threadpoolctl==3.6.0
      - tiktoken==0.7.0
      - timm==1.0.22
      - tokenizers==0.21.4
      - toml==0.10.2
      - toolz==1.1.0
      - torch==2.5.1+cu121
      - torch-fidelity==0.3.0
      - torchaudio==2.5.1+cu121
      - torchdiffeq==0.2.5
      - torchmetrics==1.8.2
      - torchprofile==0.0.4
      - torchsde==0.2.6
      - torchvision==0.20.1+cu121
      - torchx==0.7.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformer-engine==2.10.0
      - transformer-engine-cu12==2.10.0
      - transformers==4.53.3
      - trimesh==4.10.1
      - triton==3.1.0
      - typeguard==4.4.4
      - typer==0.20.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - uvicorn==0.40.0
      - wandb==0.23.1
      - wcmatch==10.1
      - wcwidth==0.2.14
      - webdataset==1.0.2
      - werkzeug==3.1.4
      - wget==3.2
      - whisper-normalizer==0.1.12
      - wrapt==2.0.1
      - xattr==1.3.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==2.18.7
      - zipp==3.23.0
prefix: /home/shixianjie/miniconda3/envs/nemo_full_v311
